# Generated by Django 5.1.1 on 2024-09-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='orden',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
