# Generated by Django 4.2.15 on 2024-10-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0001_initial'),
        ('user', '0002_remove_user_accesos_user_accesos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accesos',
            field=models.ManyToManyField(blank=True, related_name='acceso_list', to='acceso.acceso'),
        ),
    ]
