# Generated by Django 4.2.15 on 2024-10-04 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtemas',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas_relacion', to='temario.temas'),
        ),
    ]
