# Generated by Django 4.2.15 on 2024-10-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temario', '0002_alter_subtemas_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='imagen_url',
            field=models.CharField(max_length=500),
        ),
    ]
